name: OpenWrt Builder

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'
  repository_dispatch:
  workflow_dispatch:

env:
  BUILD_SCRIPT: build-scripts.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: false

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      firmware: ${{ steps.compile-scripts.outputs.firmware_json }} 
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Initialization compile environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          # 运行脚本路径
          scripts_path="${GITHUB_WORKSPACE}/scripts"  
          if [ ! -d "${scripts_path}" ]; then
              echo "Script path does not exist, Please check!"  
              exit 1
          fi

          # 查找脚本并赋予权限
          find $GITHUB_WORKSPACE/scripts -exec chmod +x {} \;

          # 检查执行脚本
          scripts_file="${GITHUB_WORKSPACE}/scripts/${BUILD_SCRIPT}"
          if [ ! -e "${scripts_file}" ]; then
              echo "Script files does not exist, Please check!"
              exit 1
          fi

          # 检查磁盘空间
          df -hT
          
          echo "scripts_path=${scripts_path}" >> $GITHUB_ENV
          echo "scripts_file=${scripts_file}" >> $GITHUB_ENV

      - name: Run compile scripts
        id: compile-scripts
        working-directory: ${{ env.scripts_path }}
        run: |
          # 执行脚本
          scripts_file=${{ env.scripts_file }}
          if [ -x "${scripts_file}" ]; then
              source ${scripts_file} 1
          fi
          
          # 检查固件信息
          if [ -z "${FIRMWARE_JSON_ARRAY}" ]; then
              echo "Firmware does not exist, Please check!"
              exit 1
          fi

          # 获取 JSON 数组 "${FIRMWARE_JSON_ARRAY}"
          JSON_ARRAY='["ubuntu-latest","macos-latest"]'
          
          list=$(echo ${JSON_ARRAY} | jq -c)

          # 设置输出
          echo "firmware_json=$(jq -c . <<< "${JSON_ARRAY}")" >> $GITHUB_OUTPUT

      - name: Set matrix
        id: set-matrix
        env:
          # 获取 JSON 字符串
          FIRMWARE_JSON: ${{ steps.compile-scripts.outputs.firmware_json}}
        run: |
          #echo "matrix=$(echo $FIRMWARE_JSON | jq -c 'map({file: .})')" >> $GITHUB_OUTPUT
          echo $FIRMWARE_JSON
          
      - name: Debug firmware-json
        run: |
          echo "firmware-json: ${{ steps.compile-scripts.outputs.firmware_json }}"   

  upload:
    needs: build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        firmware:
          ${{ fromJson(needs.build.outputs.firmware) }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Check matrix
        id: check-matrix
        run: |
          echo "Matrix: ${{ matrix.firmware }}"
          
          #firmware_list=${{ fromJson(needs.build.outputs.firmware-json) }}
          #echo "${firmware_list}"
          
          #for item in $(echo "${firmware_list}" | jq -c '.[]'); do
              #file_path=$(echo $item | jq -r '.file')
              #echo $file_path
              #echo "111"
          #done
            