name: OpenWrt Builder

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'
  repository_dispatch:
  workflow_dispatch:

env:
  BUILD_SCRIPT: build-scripts.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: false

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      firmware: ${{ steps.set-matrix.outputs.matrix }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Initialization compile environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          # 运行脚本路径
          scripts_path="${GITHUB_WORKSPACE}/scripts"  
          if [ ! -d "${scripts_path}" ]; then
              echo "Script path does not exist, Please check!"  
              exit 1
          fi

          # 查找脚本并赋予权限
          find $GITHUB_WORKSPACE/scripts -exec chmod +x {} \;

          # 检查执行脚本
          scripts_file="${GITHUB_WORKSPACE}/scripts/${BUILD_SCRIPT}"
          if [ ! -e "${scripts_file}" ]; then
              echo "Script files does not exist, Please check!"
              exit 1
          fi

          # 检查磁盘空间
          df -hT
          
          echo "scripts_path=${scripts_path}" >> $GITHUB_ENV
          echo "scripts_file=${scripts_file}" >> $GITHUB_ENV

      - name: Run compile scripts
        id: compile-scripts
        working-directory: ${{ env.scripts_path }}
        run: |
          # 执行脚本
          scripts_file=${{ env.scripts_file }}
          if [ -x "${scripts_file}" ]; then
              source ${scripts_file} 1
          fi
          
          # 检查固件信息
          if [ -z "${FIRMWARE_JSON_OBJECT}" ]; then
              echo "Firmware does not exist, Please check!"
              exit 1
          fi

          # 获取 JSON 数组 "${FIRMWARE_JSON_OBJECT}"
          # JSON_ARRAY='["ubuntu-latest","macos-latest"]'
          JSON_ARRAY=$(jq '.firmware' <<< "${FIRMWARE_JSON_OBJECT}")

          echo "firmware_object=${FIRMWARE_JSON_OBJECT}" >> $GITHUB_OUTPUT 
          
      - name: Extract Firmware Details
        id: extract_firmware_info
        run: |
          info=${{ steps.compile-scripts.outputs.firmware_object }}
          
          name=$(jq -r '.name' <<< "${info}")
          echo "$name"