name: OpenWrt Builder

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'
  repository_dispatch:
  workflow_dispatch:

env:
  BUILD_SCRIPT: build-scripts.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: false

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      firmware-json: ${{ steps.compile-scripts.outputs.firmware_json }} 
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Initialization compile environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          # 运行脚本路径
          scripts_path="${GITHUB_WORKSPACE}/scripts"  
          if [ ! -d "${scripts_path}" ]; then
              echo "Script path does not exist, Please check!"  
              exit 1
          fi

          # 查找脚本并赋予权限
          find $GITHUB_WORKSPACE/scripts -exec chmod +x {} \;

          # 检查执行脚本
          scripts_file="${GITHUB_WORKSPACE}/scripts/${BUILD_SCRIPT}"
          if [ ! -e "${scripts_file}" ]; then
              echo "Script files does not exist, Please check!"
              exit 1
          fi

          # 检查磁盘空间
          df -hT
          
          echo "scripts_path=${scripts_path}" >> $GITHUB_ENV
          echo "scripts_file=${scripts_file}" >> $GITHUB_ENV

      - name: Run compile scripts
        id: compile-scripts
        working-directory: ${{ env.scripts_path }}
        run: |
          # 执行脚本
          scripts_file=${{ env.scripts_file }}
          if [ -x "${scripts_file}" ]; then
              source ${scripts_file} 1
          fi

          # 检查固件信息
          if [ -z "${FIRMWARE_JSON_OBJECT}" ]; then
              echo "Firmware does not exist, Please check!"
              exit 1
          fi

          # 验证 JSON 对象是否为空
          if ! jq empty --argjson json "${FIRMWARE_JSON_OBJECT}" > /dev/null; then
              echo "Invalid JSON: $FIRMWARE_JSON_OBJECT"
              exit 1
          fi
          # 获取 JSON 数组
          JSON_ARRAY=$(jq '.items' <<< "${FIRMWARE_JSON_OBJECT}")
          
          # 将 JSON 字符串进行 Base64 编码
          ENCODED_JSON=$(echo -n "${FIRMWARE_JSON_OBJECT}" | base64 | tr -d '\n')
          
          # 将 Base64 编码的字符串保存到 GITHUB_ENV
          echo "encoded_json=${ENCODED_JSON}" >> $GITHUB_ENV

          # 设置输出
          echo "firmware_json=$(jq -c . <<< "${JSON_ARRAY}")" >> $GITHUB_OUTPUT

      - name: Extract Firmware Details
        id: extract_firmware_info 
        env:
          # 获取 Base64 编码的 JSON 字符串
          ENCODED_FIRMWARE_JSON: ${{ env.encoded_json }}
        run: |
          # Base64 解码 JSON 字符串
          FIRMWARE_JSON=$(echo "$ENCODED_FIRMWARE_JSON" | base64 --decode)

          # 获取 count 字段的值
          count=$(jq -r '.count' <<< "${FIRMWARE_JSON}")
          if [ ${count} -eq 0 ]; then
              echo "Firmware does not exist, Please check!"
              exit 1
          fi

          if [ ${count} -gt 1 ]; then
              name=$(jq -r '.name' <<< "${FIRMWARE_JSON}")
              path=$(jq -r '.path' <<< "${FIRMWARE_JSON}")
          else
              json_array=$(jq '.items' <<< "${FIRMWARE_JSON}")
              if [ -z "${json_array}" ] || ! jq empty <<< "${json_array}"; then
                  echo "Firmware JSON array format is invalid, Please check!"
                  exit 1
              fi

              items_object=$(jq '.[0]' <<< "${json_array}")
              if [ -z "${items_object}" ] || ! jq empty <<< "${items_object}"; then
                  echo "Firmware JSON object format is invalid, Please check!"
                  exit 1
              fi

              name=$(jq -r '.name' <<< "${items_object}")
              path=$(jq -r '.file' <<< "${items_object}")
          fi
          
          if [ -z "${name}" ] || [ -z "${path}" ]; then
              echo "Get Firmware information is Failed, please check!"
              exit 1
          fi

          # 设置输出
          echo "firmware_name=${name}" >> $GITHUB_OUTPUT
          echo "firmware_path=${path}" >> $GITHUB_OUTPUT
          
      - name: Upload firmware directory
        uses: actions/upload-artifact@v4
        if: env.UPLOAD_FIRMWARE == 'true' && 
            steps.extract_firmware_info.outputs.firmware_name != '' &&
            steps.extract_firmware_info.outputs.firmware_path != '' &&
            !cancelled()
        with:
          name: ${{ steps.extract_firmware_info.outputs.firmware_name }}
          path: ${{ steps.extract_firmware_info.outputs.firmware_path }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2  # main
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 2
          
  upload:
    needs: build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        firmware:
          ${{ fromJson(needs.build.outputs.firmware-json) }}
    steps:
      - name: Check matrix
        run: |
            echo "cur dir_name=${{ matrix.firmware.name }}"
            echo "cur dir_path=${{ matrix.firmware.path }}"      
